import 'bootstrap/dist/css/bootstrap.min.css';

// import { Button } from '../'
import { OdinApp, useAdapterEndpoint } from '../'

import { MainPage } from './MainPage';
import { EndpointPage, EndpointData_t } from './EndpointPage';
import { GraphPage } from './GraphPage';
import { LogMessagePage } from './LogMessagePage';
import { PeriodicEndpointPage } from './PeriodicEndpointPage';
import {LiveViewPage} from './LiveViewPage';
import AutoGenPage from './AutoGeneratedPage';

function App() {

  const endpoint = useAdapterEndpoint<EndpointData_t>("react", import.meta.env.VITE_ENDPOINT_URL);

  const navLinks = ["Workshop", {"Endpoints" : ["Normal", "Periodic", "AutoGenned"]}, "Graph Testing", "Log Display", "Live View", "Bootstrap"];

  return (
    <OdinApp title='Test' navLinks={navLinks}>
      <MainPage/>
      <EndpointPage endpoint={endpoint}/>
      <PeriodicEndpointPage/>
      <AutoGenPage endpoint={endpoint}/>
      <GraphPage />
      <LogMessagePage/>
      <LiveViewPage/>
    </OdinApp>
  )
}

export default App
