import 'bootstrap/dist/css/bootstrap.min.css';

import { OdinApp, useAdapterEndpoint } from "odin-react";

import { MainPage } from './MainPage';
import { EndpointPage, EndpointData } from './EndpointPage';
import { GraphPage } from './GraphPage';
import { LogMessagePage } from './LogMessagePage';
import {LiveViewPage} from './LiveViewPage';
import AutoGenPage from './AutoGeneratedPage';

function App() {

  const endpoint = useAdapterEndpoint<EndpointData>("react", import.meta.env.VITE_ENDPOINT_URL);
  const periodic_endpoint = useAdapterEndpoint<EndpointData>("react", import.meta.env.VITE_ENDPOINT_URL, 1000);

  const navLinks = ["Workshop", {"Endpoints" : ["Normal", "Periodic", "AutoGenned"]}, "Graph Testing", "Log Display", "Live View", "Bootstrap"];

  return (
    <OdinApp title='Test' navLinks={navLinks}>
      <MainPage/>
      <EndpointPage endpoint={endpoint}/>
      <EndpointPage endpoint={periodic_endpoint} />
      <AutoGenPage endpoint={endpoint}/>
      <GraphPage />
      <LogMessagePage/>
      <LiveViewPage/>
    </OdinApp>
  )
}

export default App
